<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>0f9a2f7e-1887-4201-9226-be40c64690b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3) [href=&quot;\/view_cart&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'li') and (position() = 3)]//*[@href = '/view_cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2c5392a-a61d-4607-816f-d83a2d3e254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/view_cart</value>
      <webElementGuid>5469c45d-4f54-4ed0-8e9e-4b2789959c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>e2f2860b-2858-411c-b81e-5d38f1488716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value> Cart</value>
      <webElementGuid>f8b5661b-0e32-4e50-bd95-8cf00c96665d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1a4224fff94370d494d4b7711dc0a82f</value>
      <webElementGuid>cfec423d-deee-47bc-afb9-78996fc3f1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 3)]//*[@href = '/view_cart']</value>
      <webElementGuid>5fbce87c-7e16-468a-bcf6-a9309bbf91ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 3)]//*[@href = '/view_cart']</value>
      <webElementGuid>7ccbd06a-1fb7-4959-a3fb-b7996a1d42bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/view_cart' and (text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>d01c3fa3-3a0d-47b0-89c9-507c11ee4003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
